- hosts: all
  gather_facts: False
  tasks:
  - name: install python 2
    raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)

- hosts: all
  gather_facts: True
  tasks:
  - name: install nginx
    apt:
      name: nginx
      update_cache: yes
